language: python
python:
- 2.7
install:
- pip install -r requirements-dev.txt
- pip install .
- pip install -e git+https://github.com/napalm-automation/napalm-base.git@develop#egg=napalm-base
- pip install coveralls
deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: gK2otiNZdUlFK/5smZ5iftd6zXRBzvTqA4Xw9OulVJmhIwRyMv0g/OSjLj29HYVZNr2bord7DPWD6iAeMXeHqjuiCKYmy2z4u2bIqPbRJ4G488dZM+lTGK46Uz7XtjGN24wt3EHsG++bj+Gc3aKy2K5UoxdlGaxAosr2WrGJmupLFN/upmVgJEHQFYm14ByQ4joUjPZW3zWYKOJJvCK4WY9l/v6ejYZMHlTgCFkhoxn2AjtFyItGO3YxNr6RH075d8j64WF2vihB9CBFpqqQVuzk3dSljePDF1W0goex5NqVyQa+6yRy7FAHpQbAPm6BkEbMdPIdmpThXN48M9vbZ/Avn4DXU3AZrJUw59U8vPe3IR3WrJzIjAJ1CnCoUgPZqgf0eZHezKNjs2ww1S7fVhX7iY6ahpUucGXp5Hffyv2uD9p4hT/Oiz4p2B5ZHQcN2D3AtWGYm2gNVfEPyZqZiSIel5a0BpYqPOBHiC9oKNEhTNRYU6oUL/jzZy3MJnc779qF/e70NdA4xq+TMYk6aF4yLSB0YaEjQq6dxPn6wwoPTwdrPvu8A00MSvzAZ/2mNb2KIi/dh7C3dXoxrIKN5gKJzf+YFFAgQNqtVDBrZdYghywkzH0evE8WbGSf/hv1OQsKf8TUGT0EH63n8qCdqoYjJBTjycvBdSkMXAZC5rA=
  on:
    tags: true
    branch: master
script:
- pylama .
- cd test/unit
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_bgp_config
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_bgp_neighbors
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_bgp_neighbors_detail
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_environment
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_facts
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_interfaces
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_interfaces_counters
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_lldp_neighbors
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_lldp_neighbors_detail
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_arp_table
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_ntp_peers
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_ntp_stats
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_ntp_servers
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_interfaces_ip
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_mac_address_table
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_route_to
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_snmp_information
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_probes_config
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_probes_results
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_traceroute
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_users
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_optics
- nosetests --with-coverage --cover-package napalm_junos -v TestJunOSDriver:TestGetterJunOSDriver.test_get_config
- cd ../..
- coverage combine test/unit/.coverage
after_success: coveralls
